Asymptote transform
cvxgrp/spcqe pull request #12
Opened 2024-11-06 02:42 UTC by AramisDuf

Add an option to perform extrapolation using an asymptotic model rather than linear

2024-11-06 19:47 UTC, AramisDuf commented on src/spcqe/extrapolate_asymptotic.py
remove import warnings

2024-11-06 19:47 UTC, AramisDuf commented on src/spcqe/extrapolate_asymptotic.py
update plot with neighbors

2024-11-06 19:49 UTC, AramisDuf commented on src/spcqe/extrapolate_asymptotic.py
Add 1 comment to each function + 1 file comment

2024-11-06 19:52 UTC, AramisDuf commented on src/spcqe/quantiles.py
update docstring

2024-11-06 19:53 UTC, AramisDuf commented on src/spcqe/quantiles.py
None is linear

2024-11-06 20:08 UTC, AramisDuf commented on src/spcqe/quantiles.py
inverse transform data on a time that we did not use to forward transform

2025-01-09 17:53 UTC, bmeyers requested changes

2025-01-09 17:53 UTC, bmeyers commented on notebooks/Aramis/extrapolation_demo.ipynb
discussed adding markdown cells to further explain example

2025-01-09 17:53 UTC, bmeyers commented on src/spcqe/extrapolate_asymptotic.py
> +XSOLAR = 0
consider a more useful, negative value for XSOLAR

2025-01-09 17:53 UTC, bmeyers commented on src/spcqe/quantiles.py
> +#     TODO: not used anymore. Should be removed ?
we can delete

2025-01-09 17:53 UTC, bmeyers commented on src/spcqe/quantiles.py
> +            # TODO: check if this is the correct way to extend the basis
done!

2025-01-10 09:29 UTC, AramisDuf reviewed
Good for merge

2025-01-10 09:32 UTC, AramisDuf reviewed
Good for merge

2025-01-10 19:56 UTC, bmeyers commented
Thank you @pluflou!! I think we're now ready to merge.

2025-01-10 19:58 UTC, bmeyers approved these changes

2025-01-10 19:59 UTC, merged