Sine basis
cvxgrp/spcqe pull request #5
Opened 2024-02-21 23:02 UTC by AramisDuf

Fixing bugs in trend and in "multiplying" custom basis. Inmplementing the standing wave basis.

2024-02-22 23:12 UTC, AramisDuf commented on src/spcqe/functions.py
> +
Make sphinx compliant docstring

2024-02-22 23:28 UTC, AramisDuf commented on src/spcqe/functions.py
> +    # Sanity checks
make it a helper function

2024-02-22 23:32 UTC, AramisDuf commented on src/spcqe/functions.py
> +
docstring

2024-02-22 23:32 UTC, AramisDuf commented on src/spcqe/functions.py
> +def make_regularization_matrix(num_harmonics, weight, periods, standing_wave=False, trend=False, max_cross_k=None, custom_basis=None):
test standing wave vs non standing wave

2024-02-22 23:38 UTC, AramisDuf reviewed
Completed the code review with Bennet

2024-02-22 23:39 UTC, bmeyers requested changes
Approved after comments above addressed

2024-02-26 00:56 UTC, AramisDuf commented
Resolved all the comments

2024-02-28 22:44 UTC, bmeyers approved these changes

2024-02-28 22:44 UTC, bmeyers commented on src/spcqe/functions.py
> +"""
add your name as author

2024-02-28 22:44 UTC, bmeyers commented on src/spcqe/functions.py
> +    :param num_harmonics: int or ndarray, 1D array of ints, number of harmonics to
move type to separate entries `:type arg:` style

2024-02-28 22:44 UTC, bmeyers commented on src/spcqe/functions.py
> +    :param num_harmonics: int or ndarray, 1D array of ints, number of harmonics to
same as above, add types in separate lines

2024-02-29 23:38 UTC, merged